version: "3"

services:
  mongodb:
    image: mongo:4.4.19
    ports:
      - 27017:27017
    volumes:
      - .:/usr/src
  app:
    ports:
      - 3005:3005
    env_file: .env
    build: .
    depends_on:
      - mongodb
    command: npm start